title: Orca Sightings Service
description: A cloud-based RESTful API for including orca whale sightings in the San Juan Islands in your app.

theme: just-the-docs

url: https://juliebro.github.io/orca-docs/

aux_links:
  API Doc Repository: https://github.com/juliebro/orca-docs/

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
